name: Backend CI

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-cd.yaml'

defaults:
  run:
    working-directory: backend

env:
    IMAGE_NAME: baynext-backend
    REGION: europe-west1
    ARTIFACT_REGISTRY: europe-west1-docker.pkg.dev/baynext-x1307/baynext-docker-repo

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: astral-sh/ruff-action@v3
              with:
                src: "./backend"
            
            - uses: astral-sh/ruff-action@v3
              with:
                src: "./backend"
                
            - run: ruff check app tests
            - run: ruff format app tests --check

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: astral-sh/setup-uv@v5

            - name: Install the project
              run: uv sync --locked --all-extras --dev

            - name: Run tests
              run: uv run pytest tests --cov=app

    docker:
        needs: 
            - lint
            - test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: backend/Dockerfile

            - id: gcp-auth
              name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v2
              with:
                credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

            - name: Set up Cloud SDK
              uses: "google-github-actions/setup-gcloud@v1"

            - name: Docker auth
              run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

            - name: Build image
              run: docker build . -t ${{ env.ARTIFACT_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
              working-directory: ./backend

            - name: Push image
              run: docker push ${{ env.ARTIFACT_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
