name: Backend CD

on:
    push:
        branches:
            - main
        paths:
            - 'backend/**'
            - '.github/workflows/backend-cd.yaml'

env:
    IMAGE_NAME: baynext-backend
    SERVICE_NAME: baynext-backend-service
    REGION: europe-west1
    ARTIFACT_REGISTRY: europe-west1-docker.pkg.dev/baynext-x1307/baynext-docker-repo

jobs:
    deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend
        steps:
            
            - uses: 'actions/checkout@v4'

            - id: auth
              uses: 'google-github-actions/auth@v2'
              with:
                credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
        

            - id: 'deploy'
              uses: 'google-github-actions/deploy-cloudrun@v2'
              with:
                service: ${{ env.SERVICE_NAME }}
                image: ${{ env.ARTIFACT_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
                region: ${{ env.REGION }}