name: Backend CI

on:
  pull_request:
    paths:
      - 'backend/**'

defaults:
  run:
    working-directory: backend

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run ruff
        uses: astral-sh/ruff-action@v3

      - name: Run tests
        # For example, using `pytest`
        run: uv run pytest tests --cov=app

      - name: Check dockerfile
        uses: hadolint/hadolint-action@v3.1.0
