name: Ruff
on:
    pull_request:
        paths:
            - 'backend/**'

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
            src: "./backend"
            
      - uses: hadolint/hadolint-action@v3.1.0
        with:
            dockerfile: backend/Dockerfile
