name: Deploy to PyPI

"on":
  push:
    tags:
      - 'v*'

env:
  PYTHON_VERSION: '3.12'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: libs/baynext-py
    steps:
      - uses: actions/checkout@v4

      - name: Validate tag format
        run: |
          if [[ ! "$GITHUB_REF" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo "Error: Tag must start with 'v' and follow semantic versioning (e.g., v1.0.0)"
            exit 1
          fi

      - name: Install uv
        run: pip install uv

      - name: Set version in pyproject.toml from tag
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/v}"
          uv version $TAG_VERSION

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run tests (if any exist)
        run: |
          TEST_COUNT=$(uv run pytest --collect-only 2>/dev/null | grep -o "collected [0-9]* items" | grep -o "[0-9]*" || echo "0")
          if [[ "$TEST_COUNT" -gt 0 ]]; then
            echo "Found $TEST_COUNT tests, running pytest..."
            uv run pytest
          else
            echo "No tests found, skipping test step"
          fi

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: libs/baynext-py/dist/
          password: ${{ secrets.PYPI_API_TOKEN }}