---
name: Deploy to PyPI

'on':
  push:
    tags:
      - 'v*'

defaults:
  run:
    working-directory: libs/baynext-py

permissions:
  id-token: write  # Required for trusted publishing to PyPI

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/baynext

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Build package
        run: uv build

      - name: Verify package
        run: |
          # Check that the expected files were created
          ls -la dist/
          # Verify the package can be installed
          pip install dist/*.whl
          # Test the entry point
          baynext --help

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: libs/baynext-py/dist/
