name: Deploy GCP Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

permissions:
  contents: read
  id-token: write

env:
  TF_DIR: terraform
  TF_VERSION: 1.6.6

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud with OIDC
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: ${{ env.TF_DIR }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ env.TF_DIR }}
        run: terraform plan -var="project_id=${{ vars.GCP_PROJECT_ID }}"

      - name: Terraform Apply
        working-directory: ${{ env.TF_DIR }}
        run: terraform apply -auto-approve -var="project_id=${{ vars.GCP_PROJECT_ID }}"
