# Source: https://turborepo.com/docs/guides/ci-vendors/github-actions#remote-caching-with-github-actionscache
name: Frontend CI
 
on:
  pull_request:
    paths:
        - 'frontend/**'
 
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
 
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo/cache
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
 
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
 
      - name: Install dependencies
        run: npm install --include=dev
 
      - name: Build
        run: npm run build
 
      - name: Lint
        run: npm run lint