# Source: https://gist.github.com/sjovang/5a5d82af2e5396db28c99ef5608732ef
name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

defaults:
  run:
    working-directory: terraform

env:
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
  TF_VAR_auth_secret: ${{ secrets.AUTH_SECRET }}
  TF_VAR_blob_read_write_token: ${{ secrets.VERCEL_TOKEN }}
  TF_VAR_ml_api_secret_api_key: ${{ secrets.ML_API_SECRET_API_KEY }}

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  apply:
    name: 'Apply Terraform configuration'
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - name: Authenticate to Google Cloud with OIDC
          id: auth
          uses: google-github-actions/auth@v2
          with:
            credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

        - uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: 1.6.6

        - name: Terraform fmt
          id: fmt
          run: terraform fmt -check
          
        - name: Terraform Init
          id: init
          run: terraform init
          
        - name: Terraform Validate
          id: validate
          run: terraform validate -no-color
          
        - name: Terraform Plan
          id: plan
          run: terraform plan -no-color -var="project_id=${{ env.GCP_PROJECT }}"

        - name: Terraform Apply
          run: terraform apply -input=false -auto-approve -var="project_id=${{ env.GCP_PROJECT }}"

        - name: Extract Neon Database URL from Terraform Output
          id: extract-db-url
          run: |
            DB_URL=$(terraform output -raw neon_database_url)
            echo "::add-mask::$DB_URL"
            echo "DATABASE_URL=$DB_URL" >> $GITHUB_OUTPUT

        - name: Update GitHub Repository Secret
          run: |
            gh secret set DATABASE_URL --body "${{ steps.extract-db-url.outputs.DATABASE_URL }}"
          env:
            GH_TOKEN: ${{ secrets.PAT_TOKEN }}