# Source: .github/workflows/terraform-plan.yml
name: "Terraform Plan"

on:
  pull_request:

env:
  TF_DIR: terraform
  TF_VERSION: 1.6.6
  TFPLAN_FILE: .planfile

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      # so GitHub can check out this repo using the default github.token
      contents: read
      pull-requests: write

    steps:
        - name: Checkout
          uses: actions/checkout@v4
          id: checkout

        - name: Authenticate to Google Cloud with OIDC
          id: auth
          uses: google-github-actions/auth@v2
          with:
            credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

        - name: Setup terraform
          uses: hashicorp/setup-terraform@v3
    
        - name: Init
          working-directory: ${{ env.TF_DIR }}
          run: terraform init

        - name: Validate
          working-directory: ${{ env.TF_DIR }}
          run: terraform validate
  
        - name: Plan
          working-directory: ${{ env.TF_DIR }}
          run: terraform plan -out ${{ env.TFPLAN_FILE }} -var="project_id=${{ env.GCP_PROJECT }}"

        - name: Comment
          uses: borchero/terraform-plan-comment@v2
          with:
            token: ${{ github.token }}
            working-directory: ${{ env.TF_DIR }}
            planfile: ${{ env.TFPLAN_FILE }}