# Source: https://gist.github.com/sjovang/5a5d82af2e5396db28c99ef5608732ef
name: Terraform Apply

on:
  push:
    branches:
      - main
    
env:
    TF_DIR: terraform
    TF_VERSION: 1.6.6
    TFPLAN_FILE: .planfile
      
permissions:
  id-token: write
  contents: read

jobs:
  apply:
    name: 'Apply Terraform configuration'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}
      
    - name: Init
      run: terraform init

    - name: Plan
      run: terraform plan -out ${{ env.TFPLAN_FILE }} -var="project_id=${{ env.GCP_PROJECT }}" -var="backend_bucket=${{ vars.TF_BACKEND_BUCKET }}"
      
    - name: Apply
      run: terraform apply -input=false -auto-approve ${{ env.TFPLAN_FILE }}