# Source: .github/workflows/terraform-plan.yml
name: "Terraform Plan"

on:
  pull_request:

env:
  TF_DIR: terraform
  TF_VERSION: 1.6.6

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      # so GitHub can check out this repo using the default github.token
      contents: read
      pull-requests: write

    steps:
        - name: Checkout
          id: checkout
          uses: actions/checkout@v4

        - name: Get PR ID
          id: pr-id
          shell: bash
          env:
            GITHUB_REF: ${{ inputs.github_ref }}
          run: |
            PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
            echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT  

        - name: Authenticate to Google Cloud with OIDC
          id: auth
          uses: google-github-actions/auth@v2
          with:
            credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

        - name: Setup Terraform
          id: setup
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: ${{ env.TF_VERSION }}

        - name: Terraform Init
          id: init
          working-directory: ${{ env.TF_DIR }}
          run: terraform init

        - name: Terraform Plan
          id: plan
          working-directory: ${{ env.TF_DIR }}
          shell: bash
          run: |
            echo 'plan<<EOF' >> $GITHUB_OUTPUT
            terraform plan -no-color -out=tfplan >> $GITHUB_OUTPUT
            echo 'EOF' >> $GITHUB_OUTPUT

        - name: Save Artifact
          id: save-artifact
          uses: actions/upload-artifact@v4
          with:
            path: ${{ env.TF_DIR }}/tfplan

        - name: Comment Plan
          id: comment-plan
          uses: peter-evans/create-or-update-comment@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            issue-number: ${{ steps.pr-id.outputs.PR_NUMBER }}
            body: |
                Terraform Plan:

                ```
                ${{ steps.plan.outputs.plan }}
                ```

                Plan saved to GH artifacts.