# Source: https://gist.github.com/sjovang/5a5d82af2e5396db28c99ef5608732ef
name: Terraform Apply

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: terraform
      
permissions:
  id-token: write
  contents: read

jobs:
  apply:
    name: 'Apply Terraform configuration'
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - name: Authenticate to Google Cloud with OIDC
          id: auth
          uses: google-github-actions/auth@v2
          with:
            credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

        - uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: 1.6.6

        - name: Terraform fmt
          id: fmt
          run: terraform fmt -check
          
        - name: Terraform Init
          id: init
          run: terraform init
          
        - name: Terraform Validate
          id: validate
          run: terraform validate -no-color
          
        - name: Terraform Plan
          id: plan
          run: terraform plan -no-color -var="project_id=${{ env.GCP_PROJECT }}"

        - name: Terraform Apply
          run: terraform apply -input=false -auto-approve -var="project_id=${{ env.GCP_PROJECT }}"